steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/abapfire/my1stpry:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/abapfire/my1stpry:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'abapfire', '--region=us-central1', '--platform=managed', '--image=gcr.io/abapfire/m1stpry:$SHORT_SHA']
